= Modular Power Platforms

== Building Information:
These buildings are the bases for all Modular Power buildings, and must be placed before anything else. There are currently 4 different variants: Boiler, Converter, Cooler, and Super Conductor platforms.

== Variants:

=== Boiler Platform:
These platforms are used for Modular Power Heaters and Boilers on top of the heater.

=== Converter Platform:
These platforms are used for Modular Power Turbines up to Mk2 and Generators up to HV.

=== Cooler Platform:
These platforms are used for the Co2 Chimney or Steam Chimney.

=== Super Conductor Platform:
These platforms are used for the Super HV Turbine and the Super HV Generator.

== Building Costs:

=== Boiler Platform, Converter Platform, and Cooler Platform:
* 6  Reinforced Iron Plate
* 20 Iron Rod
* 2  Modular Frame

=== Super Conductor Platform:
* 20  Heavy Modular Frame
* 50  Quickwire
* 100 Alclad Aluminium Sheet

== Dimensions:

=== Boiler Platform:
Width:  10m
Length: 20m
Height: 10m

=== Converter Platform:
Width:  10m
Length: 24m
Height: 10m

=== Cooler Platform:
Width:  10m
Length: 20m
Height: 10m

=== Super Conductor Platform:
Width:  32m
Length: 48m
Height: 20m
